language: objective-c
osx_image: xcode10.1

addons:
  homebrew:
    packages:
    - jq
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- swift -version
- fastlane unit_tests
