
default_platform(:ios)

platform :ios do
  desc "Build and run unit tests"
  lane :unit_tests  do
    swiftlint(strict: true)
    scan(
      scheme: 'Tenta-iOS',
      clean: true,
      devices: ['iPhone 7'],
      output_types: 'junit',
    )
    xcov(
      project: 'Tenta.xcodeproj',
      scheme: 'Tenta-iOS',
      output_directory: 'xcov_output'
    )
  end
end
