
default_platform(:ios)

platform :ios do
  desc "Build and run unit tests"
  lane :unit_tests  do
    begin
      github_check(
        status: :pending,
        slab: "niilohlin/Tenta",
        description: "Waiting for test result",
        target_url: "http://example.com/",
        context: "context"
      )

      swiftlint(strict: true)
      scan(
        scheme: 'Tenta-iOS',
        clean: true,
        devices: ['iPhone 7'],
        output_types: 'junit',
      )
      json = get_coverage(
        project: 'Tenta.xcodeproj',
        scheme: 'Tenta-iOS',
        output_directory: 'fastlane/test_output/xcov_output',
        html_report: false,
        json_report: true
      )
      p json
      github_check(
        status: :success,
        slab: "niilohlin/Tenta",
        description: "Success",
        target_url: "http://example.com/",
        context: "context"
      )
    rescue
      github_check(
        status: :failure,
        slab: "niilohlin/Tenta",
        description: "Failure",
        target_url: "http://example.com/",
        context: "context"
      )
    end
  end
end
